### ISSUE TITLE
Fix bar chart mapToAttributeValues error

### ISSUE THREAD

**Issue by jdaguil** [nexB/scancode-workbench#175]
The following error occurs to due mapToAttributeValues:

```
/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/rel…:870 [31mUnhandled rejection RangeError: Maximum call stack size exceeded
    at Function.map (file:///home/jono/nexb/tools/develop/aboutcode-manager/assets/js/jquery-2.1.3.min.js:2:3574)
    at Function.mapToAttributeValues (file:///home/jono/nexb/tools/develop/aboutcode-manager/assets/js/aboutCodeBarChart.js:67:18)
    at Model.aboutCodeDB.FlattenedFile.findAll.then (file:///home/jono/nexb/tools/develop/aboutcode-manager/assets/js/aboutCodeBarChart.js:56:49)
    at Model.tryCatcher (/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)[0m

printWarning @ /home/jono/nexb/tools/develop/aboutcode-manager/node_modules/sequelize/node_modules/bluebird/js/rel…:870
```
Originally reported in #174

**Comment by OmkarPh** [comment]
This is not relevant anymore, as we have a refactored version of workbench :)
